### ISSUE TITLE
elm-format

### ISSUE THREAD

**Issue by laduke** [oc-elixir-elm/diamondback-railroad#9]
And unfortunately we have to talk about 2 vs 4 spaces again. I don't have the elm17 version of the hacked elm-format that we made, so everything go changed to 4 in my recent pull request. I don't care either way about how it looks, but it might be easier for other people if we use the release version of elm-format? Or @oldfartdeveloper  has to maintain and host his version somewhere (this repo?)

**Comment by oldfartdeveloper** [comment]
I'm willing to give up on the 2 vs 4 fight.  As I noted in my comment in
your PR (which is merged btw; it looks GREAT, thanks!), elm-format breaks
the code into lines so much that the indent setting doesn't really make
that much difference.  Oh, and I don't mind the "generous" line-breaking.

So I'll get rid of my elm-format repo and use the easily downloaded one.

On Sat, Jun 4, 2016 at 11:44 PM, Travis LaDuke notifications@github.com
wrote:

> And unfortunately we have to talk about 2 vs 4 spaces again. I don't have
> the elm17 version of the hacked elm-format that we made, so everything go
> changed to 4 in my recent pull request. I don't care either way about how
> it looks, but it might be easier for other people if we use the release
> version of elm-format? Or @oldfartdeveloper
> https://github.com/oldfartdeveloper has to maintain and host his
> version somewhere (this repo?)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/oc-elixir-elm/diamondback-railroad/issues/9, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAET9C03eREwoFqktV5a1x_qZJQLjpILks5qInBCgaJpZM4IuSz7
> .

## 

Scott Smith

http://twitter.com/_ofd (OldFartDeveloper)
